create table if not exists public.emails (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text,
  body text not null,
  action text,
  tone text,
  language text,
  purpose text,
  length text,
  created_at timestamptz not null default now()
);

alter table public.emails enable row level security;

drop policy if exists "Users can view their own emails" on public.emails;
create policy "Users can view their own emails"
on public.emails for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own emails" on public.emails;
create policy "Users can insert their own emails"
on public.emails for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own emails" on public.emails;
create policy "Users can delete their own emails"
on public.emails for delete
using (auth.uid() = user_id);
